version: '3.7'
services:
  postgtesql:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_USER=app
      - POSTGRES_DB=db
